import { toPng, toSvg } from 'html-to-image'
import type { DiagramNode, DiagramEdge } from '../../types/diagram'

export async function exportPng(): Promise<void> {
  const el = document.querySelector('.react-flow__viewport') as HTMLElement | null
  if (!el) return
  const url = await toPng(el, { backgroundColor: '#ffffff', pixelRatio: 2 })
  trigger(url, 'diagram.png')
}

export async function exportSvgFile(): Promise<void> {
  const el = document.querySelector('.react-flow__viewport') as HTMLElement | null
  if (!el) return
  const url = await toSvg(el, { backgroundColor: '#ffffff' })
  trigger(url, 'diagram.svg')
}

export function exportMermaid(nodes: DiagramNode[], edges: DiagramEdge[]): void {
  const lines = ['flowchart TD']
  nodes.forEach((n) => {
    const id = n.id.replace(/-/g, '_')
    const label = (n.data.label as string).replace(/"/g, "'")
    lines.push(`  ${id}["${label}"]`)
  })
  edges.forEach((e) => {
    lines.push(`  ${e.source.replace(/-/g, '_')} --> ${e.target.replace(/-/g, '_')}`)
  })
  blob(lines.join('\n'), 'diagram.mmd')
}

export function exportTerraform(nodes: DiagramNode[], edges: DiagramEdge[]): void {
  type Gen = (n: DiagramNode) => string
  const map: Record<string, Gen> = {
    'api-gateway': (n) => tfBlock('aws_api_gateway_rest_api', n, `name = "${n.data.label as string}"`),
    'ec2':         (n) => tfBlock('aws_instance', n, `ami = "ami-0c55b159cbfafe1f0"\n  instance_type = "t3.micro"`),
    's3':          (n) => tfBlock('aws_s3_bucket', n, `bucket = "${slug(n)}-bucket"`),
    'lambda':      (n) => tfBlock('aws_lambda_function', n, `function_name = "${slug(n)}"\n  runtime = "nodejs20.x"\n  handler = "index.handler"\n  role = aws_iam_role.lambda_role.arn\n  filename = "${slug(n)}.zip"`),
    'postgres':    (n) => tfBlock('aws_db_instance', n, `engine = "postgres"\n  engine_version = "15"\n  instance_class = "db.t3.micro"\n  username = "admin"\n  password = var.db_password\n  skip_final_snapshot = true`),
    'redis':       (n) => tfBlock('aws_elasticache_cluster', n, `engine = "redis"\n  node_type = "cache.t3.micro"\n  num_cache_nodes = 1\n  parameter_group_name = "default.redis7"`),
  }

  const header = [
    '# Generated by SysDesign Visualizer — review before applying\n',
    'terraform {\n  required_providers {\n    aws = { source = "hashicorp/aws", version = "~> 5.0" }\n  }\n}\n',
    'provider "aws" { region = "us-east-1" }\n',
  ]

  const resources = nodes.map((n) => {
    const gen = map[n.data.subtype as string]
    return gen ? gen(n) : `# ${n.data.label as string} (${n.data.subtype as string}) — manual resource needed`
  })

  const deps = edges.length
    ? ['\n# Connections', ...edges.map((e) => {
        const src = nodes.find((n) => n.id === e.source)?.data.label ?? e.source
        const tgt = nodes.find((n) => n.id === e.target)?.data.label ?? e.target
        return `# ${src as string} --> ${tgt as string}`
      })]
    : []

  blob([...header, ...resources, ...deps].join('\n'), 'main.tf')
}

function slug(n: DiagramNode) {
  return (n.data.label as string).toLowerCase().replace(/[^a-z0-9]/g, '_')
}

function tfBlock(resource: string, n: DiagramNode, body: string) {
  return `resource "${resource}" "${slug(n)}" {\n  ${body}\n  tags = { Name = "${n.data.label as string}" }\n}\n`
}

function trigger(url: string, filename: string) {
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
}

function blob(content: string, filename: string) {
  const url = URL.createObjectURL(new Blob([content], { type: 'text/plain' }))
  trigger(url, filename)
  setTimeout(() => URL.revokeObjectURL(url), 1000)
}
